#!/usr/bin/env python3

from argparse import ArgumentParser
import os
import sys

with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "VERSION")) as _vf:
    __version__ = _vf.read().strip().split()[-1]

_ver_line = "║" + f"    version {__version__}".ljust(73) + "║"

logo = """
╔═════════════════════════════════════════════════════════════════════════╗
║                                                                         ║
║    ██╗███████╗ ██████╗  ██████╗ ██╗   ██╗ █████╗ ███╗   ██╗████████╗    ║
║    ██║██╔════╝██╔═══██╗██╔═══██╗██║   ██║██╔══██╗████╗  ██║╚══██╔══╝    ║
║    ██║███████╗██║   ██║██║   ██║██║   ██║███████║██╔██╗ ██║   ██║       ║
║    ██║╚════██║██║   ██║██║▄▄ ██║██║   ██║██╔══██║██║╚██╗██║   ██║       ║
║    ██║███████║╚██████╔╝╚██████╔╝╚██████╔╝██║  ██║██║ ╚████║   ██║       ║
║    ╚═╝╚══════╝ ╚═════╝  ╚══▀▀═╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝       ║
║                                                                         ║
║    BaseCode Post-Processing Pipeline                                    ║
{ver_line}
║    Powered by IsoQuant                                                  ║ 
╚═════════════════════════════════════════════════════════════════════════╝"""

if __name__ == '__main__':

    print(logo)
    sys.stdout.flush()

    aparser = ArgumentParser()

    aparser.add_argument('-c','--config',
                         help='Path to config yaml file', default='config/config.yaml')
    aparser.add_argument('-t','--threads', default=30, type=int,
                         help='Number of threads to allocate for analysis')
    aparser.add_argument('--verbose', action='store_true',
                         help='Verbose output')
    aparser.add_argument('--dry-run', action='store_true',
                         help='Perform a dry run without executing commands')

    args, unknown = aparser.parse_known_args()

    snakemake_cmd = 'snakemake -j {} --rerun-incomplete '.format(args.threads)
    if args.config != '':
        snakemake_cmd += '--configfile {} '.format(args.config)
    snakemake_cmd += '--config threads={} '.format(args.threads)
    if not args.verbose:
        snakemake_cmd += '-q all '
    if args.dry_run:
        snakemake_cmd += '--dry-run -p'
    if unknown:
        snakemake_cmd += " ".join(unknown) + " "

    os.system(snakemake_cmd)
