
### Declare your environment
library(reticulate)


use_condaenv("/Users/kawai/miniconda3/envs/R_45_python310/", required = TRUE)
use_python("/Users/kawai/miniconda3/envs/R_45_python310/bin/python", required = TRUE)
py_config()

source("/Users/kawai/Documents/git_hub/isoquant/IsoQuant_pipeline/utilities/for_R/adapter_isoquantviewer.R")


viewer<-isoquantViewer(output_directory = "~/Documents/data/runs/PR211/results/isoquant_output/",        
    prefix           = "PR211",
    reference_gtf = '~/Documents/ref/geneannotations.gff3'
      )
plot_count_bar(viewer,layer='count',gene_list=list('TSPAN6'))



plot_transcript_map(viewer,
                    gene_names=list("TSPAN6"),
                    use_transcript_model=TRUE)


reads = list('arrowhead_fraction' = 0.5,'title'='reads')
ref =  list('arrowhead_fraction' = 0.7,'title' = 'ref')
tracks_params= list('reads' = reads,'ref'=ref)

plot_genomic_region(viewer,
                    gene_name = 'TSPAN6',
                    tracks_params=tracks_params)


plot_pie_assignment(viewer,feature_to_plot = 'assignment_type')

