name: 'test_project'
reference: 'Homo_sapiens'
full_length_only: False
collapse_annotation: True
collapse_mode: cds
collapse_representative: canonical
basecode_max_gap: 550                
basecode_correct: False
basecode_keep_ambiguous_imputation: True
basecode_context_resolve: True
basecode_end_resolve: True
basecode_intron_resolve: True
data_type: pacbio_ccs
matching_strategy: precise
delta: auto
transcript_quantification: unique_only
gene_quantification: unique_splicing_consistent
model_construction_strategy: default_pacbio    
polya_requirement: auto
annotate_bam: True
duplicate_mode: all
include_imputed: True
assess_variant_support: True
variant_support_mode: both
